### ISSUE TITLE
Simplete for TiddlyWiki?

### ISSUE THREAD

**Issue by twMat** [innoq/simplete#2]
@FND  - hope it's OK to ask this here:

Simplete sounds really interesting! Given your prominent membership in the [TiddlyWiki](http://tiddlywiki.com/) ([gh](https://github.com/Jermolene/TiddlyWiki5)) community, I can't help but ask if you have any intention or ideas to make Simplete available in that context too? I.e for auto-completion within the tiddler editor.

Thank you!

**Comment by FND** [comment]
Hey Matias, it's nice to hear from you!

Given Simplete's focus on relinquishing as much control as possible to the server - essentially, it's just a widget for submitting HTML forms and navigating the server's response - I believe TiddlyWiki would at least be an untypical use case. It's possible that a TW wrapper could benefit from things already implemented here (e.g. keyboard navigation), but I'm insufficiently familiar with TW5 these days to know to what extent that would actually be useful or how it might work.

I'm gonna go ahead and close this issue, but feel free to let me know if there's anything I can clarify. Alternatively, we could discuss more concrete steps in some TiddlyWiki-related repository.
