### ISSUE TITLE
depfu support

### ISSUE THREAD

**Issue by SantoFejoDK** [innoq/simplete#3]
It would be nice to have better [depfu](https://depfu.com/) support for simplete.. currently, it doesn't show changelogs for your new versions.

I'm guessing it's because you don't have the repository set up in your package.json:
https://docs.npmjs.com/files/package.json#repository

**Comment by SantoFejoDK** [comment]
Thanks. This didn't work for the 1.5 release though. Maybe the changelog will only be seen in the next release.

**Comment by SantoFejoDK** [comment]
Just FYI, uitil has working changelogs with depfu.

**Comment by FND** [comment]
I've just released v1.6.0, hopefull that'll show up in Depfu for you.

**Comment by SantoFejoDK** [comment]
sorry, doesn't show the changelog either :-\
